export const CREATE_ITEM= 'CREATE_ITEM'
export const GET_ALL_ITEMS= 'GET_ALL_ITEMS'
export const RENT_ITEM= 'RENT_ITEM'
export const RETURN_ITEM= 'RETURN_ITEM'
export const WAIT_LIST= 'WAIT_LIST'
export const PROFILE_ITEMS= 'PROFILE_ITEMS'